### ISSUE TITLE
[1.8.9] Crash on shift click into Grinder

### ISSUE THREAD

**Issue by SwordKorn20** [TeamBR-Modding/NeoTech#49]
http://pastebin.com/bBYK10b2

**Comment by SwordKorn20** [comment]
Also happened when I tried to manually place ore in. I take it by closing it instantly you're already working on a fix?

**Comment by pauljoda** [comment]
We already fixed it. What stack were you putting in?

**Comment by SwordKorn20** [comment]
Iron ore.

**Comment by Dyonovan** [comment]
try this version. http://teambrmodding.com:8080/job/NeoTech/61/artifact/build/libs/NeoTech-1.8.9-2.2.4-B61.jar

you will need to update bookshelf to the latest available on curse

**Comment by SwordKorn20** [comment]
I'm really sorry guys. It might just be my mod mix causing some kind of rendering issue, but the problem remains regardless of which version I use of NeoTech.

**Comment by Dyonovan** [comment]
It must be something to do with another mod. Not having any issues shift clicking into the grinder.
